export const SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('active','banned','pending')),
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin')),
    number_limit_override INTEGER,
    api_enabled INTEGER NOT NULL DEFAULT 1,
    tier TEXT NOT NULL DEFAULT 'bronze' CHECK (tier IN ('bronze','silver','gold','platinum')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS numbers (
    id TEXT PRIMARY KEY,
    e164 TEXT NOT NULL UNIQUE,
    country_code TEXT NOT NULL,
    operator TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available','assigned','suspended','expired')),
    quality_score REAL NOT NULL DEFAULT 0,
    notes TEXT,
    last_sms_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    assigned_user_id TEXT
  );`,
  `CREATE TABLE IF NOT EXISTS number_assignments (
    id TEXT PRIMARY KEY,
    number_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    assigned_at TEXT NOT NULL DEFAULT (datetime('now')),
    released_at TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','released'))
  );`,
  `CREATE TABLE IF NOT EXISTS sms_messages (
    id TEXT PRIMARY KEY,
    number_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    sender TEXT NOT NULL,
    body TEXT NOT NULL,
    extracted_otp TEXT,
    country TEXT NOT NULL,
    operator TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'received' CHECK (status IN ('received','processed','failed')),
    reward_event_id TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS otps (
    id TEXT PRIMARY KEY,
    sms_id TEXT NOT NULL UNIQUE,
    number_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    code TEXT NOT NULL,
    extracted_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS reward_rules (
    id TEXT PRIMARY KEY,
    level TEXT NOT NULL CHECK (level IN ('global','per_sms','per_otp','per_country','per_operator','per_provider','per_number')),
    target TEXT,
    base_amount_cents INTEGER NOT NULL DEFAULT 0,
    multiplier REAL NOT NULL DEFAULT 1,
    priority INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    valid_from TEXT,
    valid_to TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS reward_events (
    id TEXT PRIMARY KEY,
    sms_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    rule_id TEXT NOT NULL,
    base_amount_cents INTEGER NOT NULL,
    country_multiplier REAL NOT NULL,
    operator_multiplier REAL NOT NULL,
    user_tier_multiplier REAL NOT NULL,
    final_amount_cents INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','reversed')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS wallet_balances (
    user_id TEXT PRIMARY KEY,
    pending_cents INTEGER NOT NULL DEFAULT 0,
    approved_cents INTEGER NOT NULL DEFAULT 0,
    frozen_cents INTEGER NOT NULL DEFAULT 0,
    lifetime_earned_cents INTEGER NOT NULL DEFAULT 0,
    lifetime_withdrawn_cents INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS wallet_transactions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('reward','manual_credit','manual_debit','withdrawal','reversal','bonus')),
    amount_cents INTEGER NOT NULL,
    balance_after_cents INTEGER NOT NULL,
    source_type TEXT,
    source_id TEXT,
    performed_by_user_id TEXT,
    reason TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS withdrawal_requests (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    amount_cents INTEGER NOT NULL,
    method TEXT NOT NULL CHECK (method IN ('crypto','bank_transfer','paypal','other')),
    address TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','approved','rejected','completed')),
    reviewed_by TEXT,
    reason TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    processed_at TEXT
  );`,
  `CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    number_id TEXT,
    type TEXT NOT NULL CHECK (type IN ('number_purchase','subscription')),
    status TEXT NOT NULL CHECK (status IN ('pending','completed','cancelled','refunded')),
    amount_cents INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS providers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL CHECK (type IN ('manual_pool','http_api','twilio','plivo','signalwire')),
    config TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','degraded')),
    health_score REAL NOT NULL DEFAULT 100,
    last_checked_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS provider_health_log (
    id TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('healthy','degraded','down')),
    response_time_ms INTEGER,
    error_message TEXT,
    checked_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS countries (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    base_reward_multiplier REAL NOT NULL DEFAULT 1
  );`,
  `CREATE TABLE IF NOT EXISTS operators (
    id TEXT PRIMARY KEY,
    country_code TEXT NOT NULL,
    name TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    reward_multiplier REAL NOT NULL DEFAULT 1
  );`,
  `CREATE TABLE IF NOT EXISTS api_keys (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    key_prefix TEXT NOT NULL,
    secret_hash TEXT NOT NULL,
    webhook_url TEXT,
    webhook_events TEXT NOT NULL DEFAULT '[]',
    permissions TEXT NOT NULL DEFAULT '[]',
    rate_limit_override INTEGER,
    last_used_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS api_usage_logs (
    id TEXT PRIMARY KEY,
    api_key_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    endpoint TEXT NOT NULL,
    method TEXT NOT NULL,
    status_code INTEGER NOT NULL,
    response_time_ms INTEGER NOT NULL,
    ip TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    api_key_id TEXT,
    event_type TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    url TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','success','failed','retrying')),
    attempts INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TEXT,
    next_retry_at TEXT,
    response_status INTEGER,
    response_body TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('info','warning','success','error','system')),
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    read INTEGER NOT NULL DEFAULT 0,
    data TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL,
    updated_by TEXT,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS sse_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS analytics_hour (
    bucket_hour TEXT NOT NULL,
    country_code TEXT,
    operator TEXT,
    provider_id TEXT,
    sms_count INTEGER NOT NULL DEFAULT 0,
    otp_count INTEGER NOT NULL DEFAULT 0,
    reward_total_cents INTEGER NOT NULL DEFAULT 0,
    unique_users INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket_hour, country_code, operator, provider_id)
  );`,
  `CREATE TABLE IF NOT EXISTS analytics_day (
    bucket_day TEXT NOT NULL,
    country_code TEXT,
    operator TEXT,
    provider_id TEXT,
    sms_count INTEGER NOT NULL DEFAULT 0,
    otp_count INTEGER NOT NULL DEFAULT 0,
    reward_total_cents INTEGER NOT NULL DEFAULT 0,
    unique_users INTEGER NOT NULL DEFAULT 0,
    new_users INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket_day, country_code, operator, provider_id)
  );`,
  `CREATE TABLE IF NOT EXISTS provider_health_log (
    id TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL,
    status TEXT NOT NULL,
    response_time_ms INTEGER,
    error_message TEXT,
    checked_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    changes TEXT,
    ip TEXT,
    user_agent TEXT,
    severity TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS system_logs (
    id TEXT PRIMARY KEY,
    level TEXT NOT NULL,
    category TEXT NOT NULL,
    message TEXT NOT NULL,
    context TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS _migrations (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    applied_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
] as const;

export const INDEX_SQL: string[] = [
  `CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);`,
  `CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);`,
  `CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);`,
  `CREATE INDEX IF NOT EXISTS idx_users_tier ON users(tier);`,
  `CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_country ON numbers(country_code);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_operator ON numbers(operator);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_provider ON numbers(provider_id);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_status ON numbers(status);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_assigned_user ON numbers(assigned_user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_quality ON numbers(quality_score);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_last_sms ON numbers(last_sms_at);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_created_at ON numbers(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_e164 ON numbers(e164);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_status_country ON numbers(status, country_code);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_provider_status ON numbers(provider_id, status);`,
  `CREATE INDEX IF NOT EXISTS idx_numbers_available_country ON numbers(country_code, status) WHERE status = 'available';`,
  `CREATE INDEX IF NOT EXISTS idx_assignments_number ON number_assignments(number_id);`,
  `CREATE INDEX IF NOT EXISTS idx_assignments_user ON number_assignments(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_assignments_status ON number_assignments(status);`,
  `CREATE INDEX IF NOT EXISTS idx_assignments_assigned_at ON number_assignments(assigned_at);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_number ON sms_messages(number_id);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_user ON sms_messages(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_country ON sms_messages(country);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_operator ON sms_messages(operator);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_provider ON sms_messages(provider_id);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_status ON sms_messages(status);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_created_at ON sms_messages(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_sender ON sms_messages(sender);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_otp ON sms_messages(extracted_otp) WHERE extracted_otp IS NOT NULL;`,
  `CREATE INDEX IF NOT EXISTS idx_sms_user_created ON sms_messages(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_number_created ON sms_messages(number_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_country_created ON sms_messages(country, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_status_created ON sms_messages(status, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_user_status_created ON sms_messages(user_id, status, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_body_search ON sms_messages(sender, body);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_country_operator ON sms_messages(country, operator);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_user_status ON sms_messages(user_id, status);`,
  `CREATE INDEX IF NOT EXISTS idx_sms_otp_created ON sms_messages(created_at DESC) WHERE extracted_otp IS NOT NULL;`,
  `CREATE INDEX IF NOT EXISTS idx_otps_sms ON otps(sms_id);`,
  `CREATE INDEX IF NOT EXISTS idx_otps_user ON otps(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_otps_code ON otps(code);`,
  `CREATE INDEX IF NOT EXISTS idx_otps_extracted_at ON otps(extracted_at);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_rules_level ON reward_rules(level);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_rules_target ON reward_rules(target);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_rules_active ON reward_rules(active);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_rules_priority ON reward_rules(priority DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_rules_level_priority ON reward_rules(level, priority DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_events_sms ON reward_events(sms_id);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_events_user ON reward_events(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_events_rule ON reward_events(rule_id);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_events_status ON reward_events(status);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_events_created_at ON reward_events(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_events_user_created ON reward_events(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_events_status_created ON reward_events(status, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_reward_events_rule_status ON reward_events(rule_id, status);`,
  `CREATE INDEX IF NOT EXISTS idx_wallet_tx_user_type_created ON wallet_transactions(user_id, type, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_wallet_tx_user_created ON wallet_transactions(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_wallet_tx_source ON wallet_transactions(source_type, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_wallet_tx_user_date ON wallet_transactions(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_wallet_tx_created_desc ON wallet_transactions(created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_withdrawals_user ON withdrawal_requests(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON withdrawal_requests(status);`,
  `CREATE INDEX IF NOT EXISTS idx_withdrawals_created_at ON withdrawal_requests(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_withdrawals_reviewed_by ON withdrawal_requests(reviewed_by);`,
  `CREATE INDEX IF NOT EXISTS idx_withdrawals_user_status ON withdrawal_requests(user_id, status);`,
  `CREATE INDEX IF NOT EXISTS idx_withdrawals_user_created ON withdrawal_requests(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_withdrawals_status_created ON withdrawal_requests(status, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);`,
  `CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(number_id);`,
  `CREATE INDEX IF NOT EXISTS idx_orders_user_type ON orders(user_id, type);`,
  `CREATE INDEX IF NOT EXISTS idx_orders_created_desc ON orders(created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_providers_slug ON providers(slug);`,
  `CREATE INDEX IF NOT EXISTS idx_providers_status ON providers(status);`,
  `CREATE INDEX IF NOT EXISTS idx_providers_type ON providers(type);`,
  `CREATE INDEX IF NOT EXISTS idx_providers_last_checked ON providers(last_checked_at);`,
  `CREATE INDEX IF NOT EXISTS idx_providers_health_score ON providers(health_score);`,
  `CREATE INDEX IF NOT EXISTS idx_providers_type_status ON providers(type, status);`,
  `CREATE INDEX IF NOT EXISTS idx_provider_health_provider ON provider_health_log(provider_id);`,
  `CREATE INDEX IF NOT EXISTS idx_provider_health_checked_at ON provider_health_log( CheckedAt);`.replace('CheckedAt', 'checked_at'),
  `CREATE INDEX IF NOT EXISTS idx_provider_health_provider_status ON provider_health_log(provider_id, status);`,
  `CREATE INDEX IF NOT EXISTS idx_provider_health_status_time ON provider_health_log(status, checked_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_provider_health_time_status ON provider_health_log(checked_at DESC, status);`,
  `CREATE INDEX IF NOT EXISTS idx_countries_code ON countries(code);`,
  `CREATE INDEX IF NOT EXISTS idx_countries_active ON countries(active);`,
  `CREATE INDEX IF NOT EXISTS idx_countries_code_active ON countries(code, active);`,
  `CREATE INDEX IF NOT EXISTS idx_countries_active_name ON countries(active, name);`,
  `CREATE INDEX IF NOT EXISTS idx_operators_country ON operators(country_code);`,
  `CREATE INDEX IF NOT EXISTS idx_operators_active ON operators(active);`,
  `CREATE INDEX IF NOT EXISTS idx_operators_name ON operators(name);`,
  `CREATE INDEX IF NOT EXISTS idx_operators_country_active ON operators(country_code, active);`,
  `CREATE INDEX IF NOT EXISTS idx_operators_country_name ON operators(country_code, name);`,
  `CREATE INDEX IF NOT EXISTS idx_api_keys_user ON api_keys(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_api_keys_key_prefix ON api_keys(key_prefix);`,
  `CREATE INDEX IF NOT EXISTS idx_api_keys_last_used ON api_keys(last_used_at);`,
  `CREATE INDEX IF NOT EXISTS idx_api_keys_created_at ON api_keys(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_api_keys_user_created ON api_keys(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_api_keys_user_active ON api_keys(user_id, last_used_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_key ON api_usage_logs(api_key_id);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_user ON api_usage_logs(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_endpoint ON api_usage_logs(endpoint);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_created_at ON api_usage_logs(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_ip ON api_usage_logs(ip);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_key_time ON api_usage_logs(api_key_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_user_time ON api_usage_logs(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_status_time ON api_usage_logs(status_code, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_api_usage_user_endpoint ON api_usage_logs(user_id, endpoint, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_user ON webhook_deliveries(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_api_key ON webhook_deliveries(api_key_id);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_event_type ON webhook_deliveries(event_type);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_status ON webhook_deliveries(status);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_next_retry ON webhook_deliveries(next_retry_at);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_created_at ON webhook_deliveries(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_user_status ON webhook_deliveries(user_id, status);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_apikey_status ON webhook_deliveries(api_key_id, status);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_retry_time ON webhook_deliveries(next_retry_at, status);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_event_time ON webhook_deliveries(event_type, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_url ON webhook_deliveries(url);`,
  `CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_created_status ON webhook_deliveries(created_at DESC, status);`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(read);`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, read);`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_type_created ON notifications(type, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(read, created_at DESC) WHERE read = 0;`,
  `CREATE INDEX IF NOT EXISTS idx_system_settings_category ON system_settings(category);`,
  `CREATE INDEX IF NOT EXISTS idx_system_settings_updated_at ON system_settings(updated_at);`,
  `CREATE INDEX IF NOT EXISTS idx_system_settings_category_key ON system_settings(category, key);`,
  `CREATE INDEX IF NOT EXISTS idx_sse_events_user ON sse_events(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_sse_events_type ON sse_events(event_type);`,
  `CREATE INDEX IF NOT EXISTS idx_sse_events_created_at ON sse_events(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_sse_events_user_type ON sse_events(user_id, event_type);`,
  `CREATE INDEX IF NOT EXISTS idx_sse_events_type_time ON sse_events(event_type, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_hour_bucket ON analytics_hour(bucket_hour);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_hour_country ON analytics_hour(country_code);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_hour_day_bucket ON analytics_hour(bucket_hour DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_hour_day_country ON analytics_hour(bucket_hour, country_code);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_hour_country_operator ON analytics_hour(country_code, operator);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_day_bucket ON analytics_day(bucket_day);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_day_country ON analytics_day(country_code);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_day_day_bucket ON analytics_day(bucket_day DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_day_country_provider ON analytics_day(country_code, provider_id);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_day_country_sms ON analytics_day(country_code, sms_count DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_analytics_day_new_users ON analytics_day(bucket_day, new_users DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs(resource_type, resource_id);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_severity ON audit_logs(severity);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_user_time ON audit_logs(user_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_action_time ON audit_logs(action, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_time ON audit_logs(resource_type, resource_id, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_severity_time ON audit_logs(severity, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_type ON audit_logs(resource_type);`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_user_agent ON audit_logs(user_agent);`,
  `CREATE INDEX IF NOT EXISTS idx_system_logs_level ON system_logs(level);`,
  `CREATE INDEX IF NOT EXISTS idx_system_logs_category ON system_logs(category);`,
  `CREATE INDEX IF NOT EXISTS idx_system_logs_created_at ON system_logs(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_system_logs_time ON system_logs(created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_system_logs_category_time ON system_logs(category, created_at DESC);`,
  `CREATE INDEX IF NOT EXISTS idx_system_logs_message ON system_logs(message);`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_unique ON users(email);`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_numbers_e164_unique ON numbers(e164);`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_otp_sms_unique ON otps(sms_id);`,
];
